controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_controller:
      type: mecanum_drive_controller/MecanumDriveController


mecanum_controller:
  ros__parameters:
    reference_timeout: 0.9

    # Command joints
    front_left_wheel_command_joint_name: "fl_wheel_joint"
    front_right_wheel_command_joint_name: "fr_wheel_joint"
    rear_left_wheel_command_joint_name: "rl_wheel_joint"
    rear_right_wheel_command_joint_name: "rr_wheel_joint"

    # Kinematic parameters
    kinematics:
      base_frame_offset:
        x: 0.0
        y: 0.0
        theta: 0.0
      wheels_radius: 0.05
      sum_of_robot_center_projection_on_X_Y_axis: 0.387

    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    enable_odom_tf: true

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
