controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true  # Habilitar tempo simulado para uso no Gazebo

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

mecanum_drive_controller:
  ros__parameters:
    type: mecanum_drive_controller/MecanumDriveController
    reference_timeout: 0.9

    # Joint names
    front_left_joint_name: "fl_wheel_joint"
    front_right_joint_name: "fr_wheel_joint"
    back_left_joint_name: "rl_wheel_joint"
    back_right_joint_name: "rr_wheel_joint"

    # Robot physical parameters
    wheel_base: 0.300  # Distância entre rodas no eixo X
    wheel_separation: 0.300  # Distância entre rodas no eixo Y
    wheel_radius: 0.05  # Raio das rodas (em metros)

    # Limites de velocidade e aceleração
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.5  # m/s
        min_velocity: -1.5 # m/s
        has_acceleration_limits: true
        max_acceleration: 1.0  # m/s²
        has_deceleration_limits: true
        max_deceleration: 1.0  # m/s²
      y:
        has_velocity_limits: true
        max_velocity: 1.0  # m/s
        min_velocity: -1.0 # m/s
        has_acceleration_limits: true
        max_acceleration: 0.8  # m/s²
        has_deceleration_limits: true
        max_deceleration: 0.8  # m/s²
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 3.14  # rad/s
        min_velocity: -3.14 # rad/s
        has_acceleration_limits: true
        max_acceleration: 1.57  # rad/s²
        has_deceleration_limits: true
        max_deceleration: 1.57  # rad/s²

    # Configuração de tolerância
    cmd_vel_timeout: 0.25  # Tempo limite para comandos de velocidade (em segundos)
    allow_multiple_cmd_vel_publishers: false

    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    enable_odom_tf: true

    pose_covariance_diagonal: [0.05, 0.05, 0.1, 0.1, 0.1, 0.1]
    twist_covariance_diagonal: [0.05, 0.05, 0.1, 0.1, 0.1, 0.1]
